-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 19:51:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bullet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bullet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bullet` DEFAULT CHARACTER SET utf8 ;
USE `bullet` ;

-- -----------------------------------------------------
-- Table `bullet`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullet`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `status` INT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullet`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullet`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `amount` DOUBLE NULL,
  `status` INT NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `bullet`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullet`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullet`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `status` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullet`.`products_has_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullet`.`products_has_order` (
  `products_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`products_id`, `orders_id`),
  INDEX `fk_products_has_order_order1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_products_has_order_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_order_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `bullet`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_order_order1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `bullet`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
